# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('cid', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('p_cid', models.CharField(max_length=6)),
                ('postid', models.CharField(max_length=6)),
                ('text', models.CharField(max_length=40000)),
                ('username', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='linkpost',
            fields=[
                ('postid', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='moderator',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('subredditName', models.CharField(max_length=20, primary_key=True)),
            ],
        ),
        migrations.CreateModel(
            name='submission',
            fields=[
                ('postid', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('subredditName', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='subreddit',
            fields=[
                ('subredditName', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('subscribers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='textpost',
            fields=[
                ('postid', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=40000)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
    ]
