# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddatabase', '0003_auto_20161210_0608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment_hasa_submission',
            name='id',
        ),
        migrations.RemoveField(
            model_name='comment_hasa_user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='submission_hasa_subreddit',
            name='id',
        ),
        migrations.RemoveField(
            model_name='subreddit_hasa_user',
            name='id',
        ),
        migrations.AlterField(
            model_name='comment_hasa_submission',
            name='cid',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment_hasa_user',
            name='cid',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='submission_hasa_subreddit',
            name='postid',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subreddit_hasa_user',
            name='subredditName',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
