# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddatabase', '0004_auto_20161210_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreddit_hasa_user',
            name='subredditName',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='subreddit_hasa_user',
            name='username',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
